apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.ark.mckinsey.com
  labels:
    {{- include "ark-apiserver.labels" . | nindent 4 }}
spec:
  group: ark.mckinsey.com
  version: v1alpha1
  service:
    name: {{ include "ark-apiserver.fullname" . }}
    namespace: {{ .Release.Namespace }}
    port: {{ .Values.service.port }}
  groupPriorityMinimum: 1000
  versionPriority: 15
  insecureSkipTLSVerify: true
