{{- if .Values.security.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ark-demos.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ark-demos.labels" . | nindent 4 }}
    demo.ark.mckinsey.com/component: serviceaccount
  {{- with .Values.security.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
