apiVersion: v2
name: ark-broker
description: Simple in-cluster ephemeral memory for Ark
type: application
version: 0.1.49
appVersion: 0.1.49
annotations:
  ark.mckinsey.com/service: ark-broker
  ark.mckinsey.com/resources: service
