apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-environment-variables
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://phoenix-svc.phoenix:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  CLAUDE_CODE_ENABLE_TELEMETRY: "1"
